//
//  SDL_uikitviewcontroller.swift
//  vkQuake-iOS
//
//  Created by Tobias Baumhöver on 06.07.21.
//

import UIKit

extension SDL_uikitviewcontroller {
    
    open override var prefersPointerLocked: Bool {
        return true
    }
    
    open override var prefersStatusBarHidden: Bool {
        return true
    }
    
    open override var preferredScreenEdgesDeferringSystemGestures: UIRectEdge {
        return .bottom
    }
    
    open override var prefersHomeIndicatorAutoHidden: Bool {
        setNeedsUpdateOfPrefersPointerLocked()
        return true
    }
}

extension SDL_uikitview {
    
    open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
//        return
        
        let touch = touches.first
        
//         @available(iOS 13.4, *) {
            if (touch?.type == UITouch.TouchType.indirectPointer) {
                       // ignore touch event generated by HW mouse
                       return;
            }
        super.touchesBegan(touches, with: event)
//        }
    }
    
    open override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        
//        return
        
        for touch in touches
            {
                if (touch.type == UITouch.TouchType.indirectPointer) {
                       // ignore touch event generated by HW mouse
                       return;
            }
            super.touchesEnded(touches, with: event)
        }
    }
    
    open override var isMultipleTouchEnabled: Bool {
        get {
                    return false
                }
                set {
                    super.isMultipleTouchEnabled = false
                }
    }
    
//    open override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
//        return
//    }
}
